# -*- coding: utf-8 -*-
"""bttl_lab10.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1n_S0GGkWurLMbodSouPtE0UsPW-IJFiL

Ex1
"""

T=['A',
'B','C',
None,'D','E','F',
None,None,'G','H',None,'I',None,None,
None,None,None,None,None,None,'J',None,None,None,'K','L',None,None,None,None]

t1 = [2,
     7,5,
     2,6,None,9,
     None,None,5,11,None,None,4,None]


t2 = [50,
        17,76,
        9,23,54,None,
        None,14,19,None,None,72,None,None,
        None,None,12,None,None,None,None,None,None,None,67,None,None,None,None,None]
def printLevel(t):
    n = 1
    for i in range(0,len(t)):
        print(t[i],end=" ") 
        if(2**n-2==i): 
          print('  *level',n)
          print()
          n = n+1 
printLevel(T)    
print('---------------------------')
printLevel(t1)
print('---------------------------')
printLevel(t2)

"""Ex2"""

class bNode(object):
 	def __init__(self, data=None):
 		self.left = None
 		self.right = None
 		self.data = data

A=bNode('2')
A.left =bNode('7')
A.right=bNode('5')
B=A.left 
C=A.right 
B.left =bNode('2')
B.right=bNode('6')
C.right=bNode('9')
D=B.left 
E=B.right
F=C.right
E.left =bNode('5')
E.right=bNode('11')
F.left=bNode('4')
G=E.left
H=E.right
I=F.left



a=bNode('50')

a.left=bNode('17')
a.right=bNode('76')
b=a.left 
c=a.right
b.left=bNode('9')
b.right=bNode('23')
c.left=bNode('54')
d=b.left 
e=b.right
f=c.left
d.right=bNode('14')
e.left=bNode('19')
f.right=bNode('72')
g=d.right
h=e.left
i=f.right
g.left=bNode('12')
i.left=bNode('67')
k=g.left
l=i.left

"""Ex3"""

def NLR(A):
  if A != None:
    print(A.data)
    NLR(A.left)
    NLR(A.right)


def LNR(A):
  if A:
    LNR(A.left)
    print(A.data)
    LNR(A.right)

def LRN(A):
  if A != None:
    LNR(A.left)
    LNR(A.right)
    print(A.data)

print("\n NLR: ")
NLR(A)
print("\n LNR: ")
LNR(A)
print("\n LNR: ")
LRN(A)


#abđmvsjjjs msnhsfbbncnc